import test from 'node:test';import assert from 'node:assert/strict';
import {NavigationSession,controlIntent} from '../web/core-session.mjs';import {SpeechOutput} from '../web/speech-output.mjs';
function fixture(){let now=0;const events=[],core=new NavigationSession(e=>events.push(e),()=>now);core.start();core.ready();return {core,events,at(t,mode='free_forward',direction='UNKNOWN',hazard=false){now=t;core.observe({observedAt:t,nav:{mode,direction,status:hazard?'STOP':'FREE',scan:{obstacles:hazard?[{}]:[]}}});},time(t){now=t;},speech(){return events.filter(e=>e.type==='speech_request');}};}
test('free entry once, immediate hazard, stable clear and rearm',()=>{const f=fixture();f.at(0);f.at(999);assert.equal(f.speech().length,0);f.at(1000);f.at(2000);assert.equal(f.speech().length,1);f.at(2100,'free_forward','UNKNOWN',true);f.at(2200,'free_forward','UNKNOWN',true);assert.equal(f.speech().length,2);f.at(2300);f.at(3300);f.at(3400,'free_forward','UNKNOWN',true);assert.equal(f.speech().length,3);});
test('direction must remain stable and does not repeat every frame',()=>{const f=fixture();f.at(0,'corridor','LEFT');f.at(300,'corridor','RIGHT');f.at(600,'corridor','LEFT');f.at(1099,'corridor','LEFT');assert.equal(f.speech().length,0);f.at(1100,'corridor','LEFT');assert.equal(f.speech().length,1);f.at(2000,'corridor','RIGHT');f.at(2600,'corridor','RIGHT');assert.equal(f.speech().length,1);f.at(5200,'corridor','RIGHT');assert.equal(f.speech().length,2);});
test('watchdog speaks once, rejects stale evidence and pause/stop suppress results',()=>{const f=fixture();f.time(2100);f.core.tick();f.core.tick();assert.equal(f.speech().length,1);f.core.observe({observedAt:0});assert.equal(f.speech().length,1);f.core.pause();f.at(2500,'corridor','LEFT',true);assert.equal(f.speech().length,1);f.core.resume();f.at(2600,'corridor','LEFT',true);assert.equal(f.speech().length,2);f.core.stop();f.at(2700,'corridor','RIGHT',true);assert.equal(f.speech().length,2);});
test('control commands use whole phrases, not incidental words',()=>{assert.equal(controlIntent('暂停导航。'),'pause');assert.equal(controlIntent('恢复播报'),'unmute');assert.equal(controlIntent('我没有说停止导航'),null);});
test('playback prioritizes hazard, replaces queued guidance, and discards stale queued speech',()=>{let now=0;const events=[],spoken=[];let cancelled=0;class Utterance{constructor(text){this.text=text;}}const synth={getVoices:()=>[{localService:true,lang:'zh-CN'}],speak:u=>{spoken.push(u);u.onstart();},cancel:()=>cancelled++};const output=new SpeechOutput(e=>events.push(e),{synth,Utterance,clock:()=>now});const say=(text,p=40,expiry=2000)=>output.accept({type:'speech_request',sequence:spoken.length+1,text,priority:p,expires_ms:expiry});say('left');say('right');say('forward');say('stop',100);assert.equal(cancelled,1);assert.deepEqual(spoken.map(u=>u.text),['left','stop']);say('old');now=3000;spoken.at(-1).onend();assert.equal(spoken.length,2);output.setMuted(true);say('muted',100,4000);assert.equal(spoken.length,2);assert.ok(events.some(x=>x.type==='playback_cancel'));});
test('cloud-only voice never used',()=>{const events=[];const output=new SpeechOutput(e=>events.push(e),{clock:()=>0,Utterance:class{},synth:{getVoices:()=>[{localService:false,lang:'zh-CN'}]}});output.accept({type:'speech_request',expires_ms:1000,text:'test'});assert.equal(events[0].type,'playback_error');});
