import {GuidanceAnnouncements} from './navigation.mjs';
const $=id=>document.getElementById(id),announcements=new GuidanceAnnouncements();
const events=[];let speakingHazard=false,audioContext,recognition,route=null,routeTimer=null,routeConfirmed=false,lastStep=-1,routePoints=[],lastScene=0;
function record(type,text,extra={}){const event={type,text,at:new Date().toISOString(),...extra};events.push(event);if(events.length>500)events.shift();const list=$('event-log');list.replaceChildren();for(const e of events.slice(-12).reverse()){const li=document.createElement('li'),time=document.createElement('time');time.textContent=e.at.slice(11,19)+' · '+e.type;li.append(time,document.createTextNode(e.text));list.append(li);}window.prtsEvents=events;}
function tone(hazard=false){if(!$('cue-enabled').checked)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();void audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=hazard?620:880;g.gain.setValueAtTime(.08,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.16);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.18);}catch{record('audio','浏览器未提供提示音输出');}}
function say(text,hazard=false){if(speakingHazard&&!hazard&&window.speechSynthesis?.speaking)return;tone(hazard);if(!$('tts-enabled').checked)return;if(!window.speechSynthesis){record('audio','此浏览器不支持系统 TTS');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=1.05;speakingHazard=hazard;utterance.onend=utterance.onerror=()=>{speakingHazard=false;};speechSynthesis.speak(utterance);}
function stopSpeech(){speakingHazard=false;window.speechSynthesis?.cancel();}
$('tts-enabled').onchange=()=>{if(!$('tts-enabled').checked)stopSpeech();};$('test-sound').onclick=()=>{say('PRTS 语音提示已准备好');record('audio','试听已请求；请先启用所需的语音或提示音开关');};$('mute-now').onclick=stopSpeech;
function selectSource(name){document.querySelectorAll('.source-tabs button').forEach(b=>b.classList.toggle('selected',b.id==='use-'+name));}
window.addEventListener('prts-source',e=>selectSource(e.detail));
$('use-street').onclick=async()=>{selectSource('street');await window.prtsControls.source('street');};
$('use-sample').onclick=async()=>{selectSource('sample');await window.prtsControls.source('sample');};$('use-camera').onclick=async()=>{selectSource('camera');await window.prtsControls.source('camera');};$('use-file').onclick=()=>{$('settings').click();$('input-source').value='file';$('input-source').dispatchEvent(new Event('change'));};
$('forward-angle').oninput=()=>{$('angle-label').textContent='±'+$('forward-angle').value+'°';};
window.addEventListener('prts-start',()=>{announcements.reset();record('session','加载感知模型');});
window.addEventListener('prts-stop',()=>{announcements.reset();stopSpeech();$('nav-mode').textContent='已停止';$('nav-instruction').textContent='感知已停止，不再生成导航提示。';record('session','停止相机与感知');});
window.addEventListener('prts-perception',({detail:d})=>{
 const nav=d.nav;$('object-count').textContent=d.detections.length;$('detector-time').textContent=Math.round(d.detectorMs)+' ms';$('evidence-age').textContent=(d.ageMs/1000).toFixed(1)+' s';
 $('nav-mode').textContent=nav.mode==='free_forward'?'自由前进':'候选通道';$('nav-mode').dataset.status=nav.status;$('nav-instruction').textContent=nav.text;
 const stale=d.ageMs>2000;
 if(stale){$('nav-mode').textContent='观测延迟';$('nav-instruction').textContent='当前结果超过 2 秒，仅展示回放分析，暂不播报导航。';}
 else{const text=announcements.update(nav,performance.now()/1000);if(text){record('guidance',text,{mode:nav.mode,status:nav.status,halfAngle:Number($('forward-angle').value),ageMs:d.ageMs});say(text,nav.status==='STOP');}}
 if(performance.now()-lastScene>1000){lastScene=performance.now();window.prtsLatestScene={type:'scene',mode:nav.mode,status:nav.status,objects:d.detections,path:d.points,coordinateSpace:'image',ageMs:d.ageMs};}
});
async function command(text){record('command',text);if(/公交|叫号|看.*什么|读|地铁|等.*车/.test(text)){record('feature','这项请求需要大脑，本 Web 版本暂未开放。');say('这项功能需要大脑，暂未开放');return;}
 if(/停止|暂停/.test(text)){stopRoute();window.prtsControls.stop();return;}
 if(/开始|启动|继续/.test(text)){await window.prtsControls.start();return;}
 record('command_help','当前支持：开始导航、停止导航。目的地请在路线实验中确认。');}
$('command-form').onsubmit=e=>{e.preventDefault();const text=$('command').value.trim();if(text){$('command').value='';void command(text);}};
$('voice-command').onclick=()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('voice-status').textContent='此浏览器没有语音识别接口，请使用文字指令。';return;}if(recognition){recognition.stop();return;}recognition=new Recognition();recognition.lang='zh-CN';recognition.interimResults=false;recognition.onresult=e=>{const text=e.results[0][0].transcript;$('voice-status').textContent='识别：'+text;void command(text);};recognition.onerror=e=>{$('voice-status').textContent='语音输入失败：'+e.error+'。可继续使用文字指令。';};recognition.onend=()=>{recognition=null;$('voice-command').textContent='使用浏览器语音输入';};recognition.start();$('voice-status').textContent='正在听取控制指令；音频可能通过浏览器厂商服务处理。';$('voice-command').textContent='结束语音输入';};
$('export-events').onclick=()=>{const blob=new Blob([JSON.stringify({schemaVersion:1,scope:'Web light-model test; no VLM; route positions are simulated',events,latestScene:window.prtsLatestScene||null},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='prts-web-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
const haversine=(a,b)=>{const r=Math.PI/180,p=(b.latitude-a.latitude)*r,q=(b.longitude-a.longitude)*r;return 6371000*2*Math.asin(Math.min(1,Math.sqrt(Math.sin(p/2)**2+Math.cos(a.latitude*r)*Math.cos(b.latitude*r)*Math.sin(q/2)**2)));};
function stopRoute(){clearInterval(routeTimer);routeTimer=null;}
function loadRoute(value,source){
 if(!value?.destination?.name||!Array.isArray(value.steps)||!value.steps.length)throw new Error('需要 destination.name 和非空 steps[].points 路线格式');
 const points=value.steps.flatMap((step,index)=>{if(!Array.isArray(step.points)||!step.points.length)throw new Error('路线步骤缺少 points');return step.points.map(p=>({...p,step:index}));});
 if(points.length<2||points.length>20000||points.some(p=>!Number.isFinite(p.longitude)||!Number.isFinite(p.latitude)||Math.abs(p.longitude)>180||Math.abs(p.latitude)>90||p.crs!=='GCJ02'))throw new Error('请使用有效 GCJ02 经纬度路线点（2–20000 个）');
 stopRoute();route=value;routePoints=points;routeConfirmed=false;lastStep=-1;$('route-progress').value=0;
 let distance=0;points.forEach((p,i)=>{if(i)distance+=haversine(points[i-1],p);p.distance=distance;});if(distance<1)throw new Error('路线长度不足');
 const x=points.map(p=>p.longitude),y=points.map(p=>p.latitude),minX=Math.min(...x),maxY=Math.max(...y),dx=Math.max(...x)-minX,dy=maxY-Math.min(...y),lat=points[0].latitude*Math.PI/180,sx=Math.cos(lat);const scale=Math.min(550/Math.max(dx*sx,1e-8),220/Math.max(dy,1e-8));
 points.forEach(p=>{p.x=35+(p.longitude-minX)*sx*scale;p.y=35+(maxY-p.latitude)*scale;});
 $('route-line').setAttribute('d',points.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' '));$('destination-name').textContent=value.destination.name;$('route-distance').textContent=Math.round(distance)+' m · '+value.steps.length+' 个步骤';$('route-source').textContent=source;$('route-description').textContent='GCJ-02 路线示意 · 标记是模拟位置，不对应视频中的位置';$('route-instruction').textContent='请确认目的地后开始模拟回放。';updateRoute(0,false);
}
function updateRoute(percent,notify=true){if(!route)return;const total=routePoints.at(-1).distance,target=percent/100*total;const p=routePoints.find(p=>p.distance>=target)||routePoints.at(-1);$('route-marker').setAttribute('cx',p.x);$('route-marker').setAttribute('cy',p.y);$('route-percent').textContent=Math.round(percent)+'%';if(!routeConfirmed)return;const step=route.steps[p.step];const text=percent>=100?'模拟到达目的地':step.instruction||step.action||'沿当前路线继续';$('route-instruction').textContent=text;if(notify&&(lastStep!==p.step||percent>=100)){record(percent>=100?'route_arrival':'route_step',text,{simulated:true,step:p.step});say(text);}lastStep=p.step;if(percent>=100)stopRoute();}
$('route-progress').oninput=()=>{stopRoute();updateRoute(Number($('route-progress').value));};
$('confirm-route').onclick=()=>{if(!route)return;if(Number($('route-progress').value)>=100)$('route-progress').value=0;routeConfirmed=true;record('route_confirm','已确认：'+route.destination.name,{simulated:true});stopRoute();updateRoute(Number($('route-progress').value));routeTimer=setInterval(()=>{const v=Math.min(100,Number($('route-progress').value)+.5);$('route-progress').value=v;updateRoute(v);},200);};
$('pause-route').onclick=stopRoute;$('reset-route').onclick=()=>{stopRoute();routeConfirmed=false;lastStep=-1;$('route-progress').value=0;updateRoute(0,false);$('route-instruction').textContent='已重置，请重新确认目的地。';};
$('route-file').onchange=async e=>{try{loadRoute(JSON.parse(await e.target.files[0].text()),'导入路线 · 模拟位置');record('route_import','已导入路线，等待确认');}catch(error){$('map-status').textContent=error.message;}};
async function amap(path,params){const key=$('map-key').value.trim();if(!key)throw new Error('请填写自己的高德 Key');const response=await fetch('https://restapi.amap.com/v3/'+path+'?'+new URLSearchParams({...params,key}));const value=await response.json();if(value.status!=='1')throw new Error(value.info||'查询失败');return value;}
$('search-destination').onclick=async()=>{const button=$('search-destination');button.disabled=true;$('map-status').textContent='查询中…';$('destination-results').replaceChildren();try{const keywords=$('destination-query').value.trim();if(!keywords)throw new Error('请输入目的地名称');const response=await amap('place/text',{keywords,offset:'5'});for(const poi of response.pois||[]){const b=document.createElement('button');b.textContent=poi.name+' · '+(Array.isArray(poi.address)?'':poi.address);b.onclick=async()=>{try{const origin=$('route-origin').value.trim();if(!/^-?\d+(\.\d+)?,-?\d+(\.\d+)?$/.test(origin))throw new Error('起点请填写 GCJ-02 经度,纬度');$('map-status').textContent='规划步行路线…';const result=await amap('direction/walking',{origin,destination:poi.location});const path=result.route?.paths?.[0];if(!path)throw new Error('没有返回可用步行路线');loadRoute({destination:{name:poi.name},steps:path.steps.map(s=>({...s,points:s.polyline.split(';').map(p=>{const [longitude,latitude]=p.split(',').map(Number);return {longitude,latitude,crs:'GCJ02'};})}))},'实时高德查询 · 模拟位置');$('map-status').textContent='已获取路线；请确认目的地开始回放。';}catch(error){$('map-status').textContent=error.message;}};$('destination-results').append(b);}$('map-status').textContent=response.pois?.length?'选择候选目的地来规划路线。':'没有找到目的地。';}catch(error){$('map-status').textContent=error.message+' 可使用内置路线或导入 JSON。';}finally{button.disabled=false;}};
fetch('./data/route.json').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(r=>loadRoute(r,'已保存的高德路线')).catch(e=>{$('route-description').textContent='内置路线加载失败：'+e.message;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRoute();stopSpeech();recognition?.stop();}});window.addEventListener('pagehide',()=>{stopRoute();recognition?.stop();});
record('ready','小脑 Web 体验已就绪；大脑功能未加载');
